### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by marcusosterberg** [Webperf-se/webperf_core#1]
Need to be updated, also include setup instructions for beginners.

**Comment by marcusosterberg** [comment]
Preferably someone else tries the setup instructions :)

**Comment by marcusosterberg** [comment]
Additions (in Swedish, sorry):
* Förklara hur man sätter upp en venv-miljö (och att det är bra att uppdatera pip direkt efter)
* Hantera att folk kan ha både Python 2 & 3, eller bara 2

**Comment by flowertwig-org** [comment]
Enda problemet jag hade var utf-8 encoding (ändrade kod för att stödja det) och att jag var tvungen att använda Python 3.8.
Resten gick hur smidigt som helst.

**Comment by 7h3Rabbit** [comment]
The documentation has been rewritten since this issue was added and we know by now that multiple people have successfully setup webperf-core.
We have also been able to point to the documentation for many of the questions regarding setup in slack channel.

Closing issue and if the need ever comes up again we will just open a new ticket for the specific thing that needs to improve
