### ISSUE TITLE
PyLint for Improved Code Quality - tests/frontend_quality_yellow_lab_tools.py

### ISSUE THREAD

**Issue by cockroacher** [Webperf-se/webperf_core#316]
************* Module tests.frontend_quality_yellow_lab_tools
tests/frontend_quality_yellow_lab_tools.py:97:0: C0301: Line too long (153/100) (line-too-long)
tests/frontend_quality_yellow_lab_tools.py:1:0: C0114: Missing module docstring (missing-module-docstring)
tests/frontend_quality_yellow_lab_tools.py:5:0: E0401: Unable to import 'requests' (import-error)
tests/frontend_quality_yellow_lab_tools.py:6:0: E0401: Unable to import 'config' (import-error)
tests/frontend_quality_yellow_lab_tools.py:7:0: W0401: Wildcard import tests.utils (wildcard-import)
tests/frontend_quality_yellow_lab_tools.py:15:0: R1731: Consider using 'time_sleep = max(time_sleep, 5)' instead of unnecessary if block (consider-using-max-builtin)
tests/frontend_quality_yellow_lab_tools.py:16:4: C0103: Constant name "time_sleep" doesn't conform to UPPER_CASE naming style (invalid-name)
tests/frontend_quality_yellow_lab_tools.py:20:0: W0702: No exception type(s) specified (bare-except)
tests/frontend_quality_yellow_lab_tools.py:22:4: C0103: Constant name "ylt_server_address" doesn't conform to UPPER_CASE naming style (invalid-name)
tests/frontend_quality_yellow_lab_tools.py:26:0: W0702: No exception type(s) specified (bare-except)
tests/frontend_quality_yellow_lab_tools.py:28:4: C0103: Constant name "ylt_use_api" doesn't conform to UPPER_CASE naming style (invalid-name)
tests/frontend_quality_yellow_lab_tools.py:31:16: C0103: Argument name "langCode" doesn't conform to snake_case naming style (invalid-name)
tests/frontend_quality_yellow_lab_tools.py:31:0: R0914: Too many local variables (35/15) (too-many-locals)
tests/frontend_quality_yellow_lab_tools.py:37:4: W0621: Redefining name 'time' from outer scope (line 7) (redefined-outer-name)
tests/frontend_quality_yellow_lab_tools.py:37:4: C0415: Import outside toplevel (time) (import-outside-toplevel)
tests/frontend_quality_yellow_lab_tools.py:51:26: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/frontend_quality_yellow_lab_tools.py:56:23: E1101: Module 'json' has no 'loads' member (no-member)
tests/frontend_quality_yellow_lab_tools.py:62:16: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/frontend_quality_yellow_lab_tools.py:63:27: E1101: Module 'json' has no 'loads' member (no-member)
tests/frontend_quality_yellow_lab_tools.py:67:21: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/frontend_quality_yellow_lab_tools.py:71:8: C0415: Import outside toplevel (subprocess) (import-outside-toplevel)
tests/frontend_quality_yellow_lab_tools.py:74:8: C0103: Variable name "bashCommand" doesn't conform to snake_case naming style (invalid-name)
tests/frontend_quality_yellow_lab_tools.py:74:22: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/frontend_quality_yellow_lab_tools.py:83:18: E1101: Module 'json' has no 'loads' member (no-member)
tests/frontend_quality_yellow_lab_tools.py:157:4: W0702: No exception type(s) specified (bare-except)
tests/frontend_quality_yellow_lab_tools.py:123:25: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/frontend_quality_yellow_lab_tools.py:31:0: R0912: Too many branches (16/12) (too-many-branches)
tests/frontend_quality_yellow_lab_tools.py:31:0: R0915: Too many statements (73/50) (too-many-statements)
tests/frontend_quality_yellow_lab_tools.py:76:18: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
tests/frontend_quality_yellow_lab_tools.py:77:16: W0612: Unused variable 'error' (unused-variable)
tests/frontend_quality_yellow_lab_tools.py:126:12: W0612: Unused variable 'matching_one_category_or_more' (unused-variable)
tests/frontend_quality_yellow_lab_tools.py:158:8: W0612: Unused variable 'do' (unused-variable)
tests/frontend_quality_yellow_lab_tools.py:182:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/frontend_quality_yellow_lab_tools.py:184:4: R1730: Consider using 'points = min(points, 5.0)' instead of unnecessary if block (consider-using-min-builtin)
tests/frontend_quality_yellow_lab_tools.py:186:4: R1731: Consider using 'points = max(points, 1.0)' instead of unnecessary if block (consider-using-max-builtin)
tests/frontend_quality_yellow_lab_tools.py:188:19: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/frontend_quality_yellow_lab_tools.py:3:0: C0411: standard import "datetime" should be placed before first party import "models.Rating"  (wrong-import-order)
tests/frontend_quality_yellow_lab_tools.py:4:0: C0411: standard import "json" should be placed before first party import "models.Rating"  (wrong-import-order)
tests/frontend_quality_yellow_lab_tools.py:5:0: C0411: third party import "requests" should be placed before first party import "models.Rating"  (wrong-import-order)
tests/frontend_quality_yellow_lab_tools.py:6:0: C0411: third party import "config" should be placed before first party import "models.Rating"  (wrong-import-order)
tests/frontend_quality_yellow_lab_tools.py:8:0: C0411: standard import "gettext" should be placed before third party imports "requests", "config" and first party imports "models.Rating", "tests.utils.*"  (wrong-import-order)
tests/frontend_quality_yellow_lab_tools.py:7:0: W0614: Unused import(s) hashlib, shutil, sys, socket, ssl, time, urllib, uuid, re, dns, IP2Location, ip2location_db, ex, useragent, googlePageSpeedApiKey, gitHubApiKey, use_cache, cache_time_delta, dns_server, change_url_to_test_url, is_file_older_than, get_cache_path, get_cache_file, has_cache_file, clean_cache_files, set_cache_file, get_content_type, get_url_headers, has_redirect, get_guid, convert_to_seconds, is_sitemap, dns_lookup, dns_response_to_list, get_eu_countries, get_exception_countries, is_country_code_in_eu, is_country_code_in_exception_list, is_country_code_in_eu_or_on_exception_list, get_country_code_from_ip2location, get_best_country_code, get_friendly_url_name, timedelta, Path, BeautifulSoup, ParseResult, urlparse and urlunparse from wildcard import of tests.utils (unused-wildcard-import)

**Comment by 7h3Rabbit** [comment]
tests/frontend_quality_yellow_lab_tools.py:81:0: C0301: Line too long (181/100) (line-too-long)
tests/frontend_quality_yellow_lab_tools.py:14:0: R1731: Consider using 'time_sleep = max(time_sleep, 5)' instead of unnecessary if block (consider-using-max-builtin)
tests/frontend_quality_yellow_lab_tools.py:15:4: C0103: Constant name "time_sleep" doesn't conform to UPPER_CASE naming style (invalid-name)
tests/frontend_quality_yellow_lab_tools.py:20:0: R0914: Too many local variables (34/15) (too-many-locals)
tests/frontend_quality_yellow_lab_tools.py:36:12: W3101: Missing timeout argument for method 'requests.post' can cause your program to hang indefinitely (missing-timeout)
tests/frontend_quality_yellow_lab_tools.py:36:26: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/frontend_quality_yellow_lab_tools.py:47:16: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/frontend_quality_yellow_lab_tools.py:52:21: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/frontend_quality_yellow_lab_tools.py:56:8: C0415: Import outside toplevel (subprocess) (import-outside-toplevel)
tests/frontend_quality_yellow_lab_tools.py:58:18: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/frontend_quality_yellow_lab_tools.py:141:4: W0702: No exception type(s) specified (bare-except)
tests/frontend_quality_yellow_lab_tools.py:107:25: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/frontend_quality_yellow_lab_tools.py:20:0: R0912: Too many branches (16/12) (too-many-branches)
tests/frontend_quality_yellow_lab_tools.py:20:0: R0915: Too many statements (70/50) (too-many-statements)
tests/frontend_quality_yellow_lab_tools.py:60:18: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
tests/frontend_quality_yellow_lab_tools.py:110:12: W0612: Unused variable 'matching_one_category_or_more' (unused-variable)
tests/frontend_quality_yellow_lab_tools.py:142:8: W0612: Unused variable 'do' (unused-variable)
tests/frontend_quality_yellow_lab_tools.py:166:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/frontend_quality_yellow_lab_tools.py:168:4: R1730: Consider using 'points = min(points, 5.0)' instead of unnecessary if block (consider-using-min-builtin)
tests/frontend_quality_yellow_lab_tools.py:170:4: R1731: Consider using 'points = max(points, 1.0)' instead of unnecessary if block (consider-using-max-builtin)
tests/frontend_quality_yellow_lab_tools.py:172:19: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
