### ISSUE TITLE
PyLint for Improved Code Quality - tests/performance_sitespeed_io.py

### ISSUE THREAD

**Issue by cockroacher** [Webperf-se/webperf_core#322]
************* Module tests.performance_sitespeed_io
tests/performance_sitespeed_io.py:23:0: C0301: Line too long (104/100) (line-too-long)
tests/performance_sitespeed_io.py:116:0: C0301: Line too long (129/100) (line-too-long)
tests/performance_sitespeed_io.py:117:0: C0301: Line too long (122/100) (line-too-long)
tests/performance_sitespeed_io.py:145:0: C0301: Line too long (135/100) (line-too-long)
tests/performance_sitespeed_io.py:151:0: C0301: Line too long (144/100) (line-too-long)
tests/performance_sitespeed_io.py:154:0: C0301: Line too long (334/100) (line-too-long)
tests/performance_sitespeed_io.py:157:0: C0301: Line too long (331/100) (line-too-long)
tests/performance_sitespeed_io.py:175:0: C0301: Line too long (135/100) (line-too-long)
tests/performance_sitespeed_io.py:181:0: C0301: Line too long (144/100) (line-too-long)
tests/performance_sitespeed_io.py:184:0: C0301: Line too long (291/100) (line-too-long)
tests/performance_sitespeed_io.py:187:0: C0301: Line too long (288/100) (line-too-long)
tests/performance_sitespeed_io.py:199:0: C0301: Line too long (258/100) (line-too-long)
tests/performance_sitespeed_io.py:257:22: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/performance_sitespeed_io.py:271:22: E1306: Not enough arguments for format string (too-few-format-args)
tests/performance_sitespeed_io.py:271:22: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/performance_sitespeed_io.py:302:34: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/performance_sitespeed_io.py:224:0: R0912: Too many branches (20/12) (too-many-branches)
tests/performance_sitespeed_io.py:224:0: R0915: Too many statements (60/50) (too-many-statements)
tests/performance_sitespeed_io.py:309:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/performance_sitespeed_io.py:309:0: R0914: Too many local variables (26/15) (too-many-locals)
tests/performance_sitespeed_io.py:315:8: C0103: Variable name "matchNum" doesn't conform to snake_case naming style (invalid-name)
tests/performance_sitespeed_io.py:320:29: R1734: Consider using [] instead of list() (use-list-literal)
tests/performance_sitespeed_io.py:339:12: R1731: Consider using 'biggest = max(biggest, number)' instead of unnecessary if block (consider-using-max-builtin)
tests/performance_sitespeed_io.py:436:19: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/performance_sitespeed_io.py:309:0: R0912: Too many branches (43/12) (too-many-branches)
tests/performance_sitespeed_io.py:309:0: R0915: Too many statements (103/50) (too-many-statements)
tests/performance_sitespeed_io.py:315:8: W0612: Unused variable 'matchNum' (unused-variable)
tests/performance_sitespeed_io.py:5:0: C0411: standard import "datetime" should be placed before first party import "models.Rating"  (wrong-import-order)
tests/performance_sitespeed_io.py:6:0: C0411: third party import "config" should be placed before first party import "models.Rating"  (wrong-import-order)
tests/performance_sitespeed_io.py:8:0: C0411: standard import "gettext" should be placed before third party import "config" and first party imports "models.Rating", "tests.utils.*"  (wrong-import-order)
tests/performance_sitespeed_io.py:7:0: W0614: Unused import(s) hashlib, shutil, sys, socket, ssl, time, requests, urllib, uuid, dns, IP2Location, ip2location_db, ex, useragent, googlePageSpeedApiKey, gitHubApiKey, use_cache, cache_time_delta, dns_server, change_url_to_test_url, is_file_older_than, get_cache_path, get_cache_file, has_cache_file, clean_cache_files, set_cache_file, httpRequestGetContent, get_content_type, get_url_headers, has_redirect, get_guid, convert_to_seconds, is_sitemap, dns_lookup, dns_response_to_list, get_eu_countries, get_exception_countries, is_country_code_in_eu, is_country_code_in_exception_list, is_country_code_in_eu_or_on_exception_list, get_country_code_from_ip2location, get_best_country_code, get_friendly_url_name, timedelta, BeautifulSoup, ParseResult, urlparse and urlunparse from wildcard import of tests.utils (unused-wildcard-import)

**Comment by 7h3Rabbit** [comment]
tests/performance_sitespeed_io.py:112:0: C0301: Line too long (129/100) (line-too-long)
tests/performance_sitespeed_io.py:113:0: C0301: Line too long (122/100) (line-too-long)
tests/performance_sitespeed_io.py:141:0: C0301: Line too long (135/100) (line-too-long)
tests/performance_sitespeed_io.py:147:0: C0301: Line too long (144/100) (line-too-long)
tests/performance_sitespeed_io.py:150:0: C0301: Line too long (334/100) (line-too-long)
tests/performance_sitespeed_io.py:153:0: C0301: Line too long (331/100) (line-too-long)
tests/performance_sitespeed_io.py:171:0: C0301: Line too long (135/100) (line-too-long)
tests/performance_sitespeed_io.py:177:0: C0301: Line too long (144/100) (line-too-long)
tests/performance_sitespeed_io.py:180:0: C0301: Line too long (291/100) (line-too-long)
tests/performance_sitespeed_io.py:183:0: C0301: Line too long (288/100) (line-too-long)
tests/performance_sitespeed_io.py:195:0: C0301: Line too long (258/100) (line-too-long)
tests/performance_sitespeed_io.py:198:0: C0301: Line too long (255/100) (line-too-long)
tests/performance_sitespeed_io.py:208:0: C0301: Line too long (272/100) (line-too-long)
tests/performance_sitespeed_io.py:211:0: C0301: Line too long (269/100) (line-too-long)
tests/performance_sitespeed_io.py:220:0: C0301: Line too long (102/100) (line-too-long)
tests/performance_sitespeed_io.py:267:0: C0301: Line too long (105/100) (line-too-long)
tests/performance_sitespeed_io.py:308:0: C0301: Line too long (172/100) (line-too-long)
tests/performance_sitespeed_io.py:412:0: C0301: Line too long (109/100) (line-too-long)
tests/performance_sitespeed_io.py:13:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/performance_sitespeed_io.py:21:18: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/performance_sitespeed_io.py:24:8: C0415: Import outside toplevel (subprocess) (import-outside-toplevel)
tests/performance_sitespeed_io.py:29:8: C0415: Import outside toplevel (subprocess) (import-outside-toplevel)
tests/performance_sitespeed_io.py:31:18: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/performance_sitespeed_io.py:34:18: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
tests/performance_sitespeed_io.py:43:0: R0914: Too many local variables (21/15) (too-many-locals)
tests/performance_sitespeed_io.py:96:15: W0631: Using possibly undefined loop variable 'validator' (undefined-loop-variable)
tests/performance_sitespeed_io.py:100:15: W0631: Using possibly undefined loop variable 'validator' (undefined-loop-variable)
tests/performance_sitespeed_io.py:110:29: C0121: Comparison 'reference_rating != None' should be 'reference_rating is not None' (singleton-comparison)
tests/performance_sitespeed_io.py:113:41: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/performance_sitespeed_io.py:122:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/performance_sitespeed_io.py:129:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
tests/performance_sitespeed_io.py:134:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/performance_sitespeed_io.py:140:41: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/performance_sitespeed_io.py:146:41: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/performance_sitespeed_io.py:150:10: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/performance_sitespeed_io.py:153:14: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/performance_sitespeed_io.py:164:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/performance_sitespeed_io.py:170:41: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/performance_sitespeed_io.py:176:41: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/performance_sitespeed_io.py:180:10: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/performance_sitespeed_io.py:183:14: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/performance_sitespeed_io.py:194:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/performance_sitespeed_io.py:195:10: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/performance_sitespeed_io.py:198:14: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/performance_sitespeed_io.py:207:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/performance_sitespeed_io.py:208:10: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/performance_sitespeed_io.py:211:14: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/performance_sitespeed_io.py:220:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/performance_sitespeed_io.py:220:0: R0914: Too many local variables (21/15) (too-many-locals)
tests/performance_sitespeed_io.py:223:20: E0602: Undefined variable '_' (undefined-variable)
tests/performance_sitespeed_io.py:227:7: C0121: Comparison 'reference_result_dict != None' should be 'reference_result_dict is not None' (singleton-comparison)
tests/performance_sitespeed_io.py:253:22: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/performance_sitespeed_io.py:267:22: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/performance_sitespeed_io.py:292:34: E0602: Undefined variable '_' (undefined-variable)
tests/performance_sitespeed_io.py:298:34: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/performance_sitespeed_io.py:220:0: R0912: Too many branches (20/12) (too-many-branches)
tests/performance_sitespeed_io.py:220:0: R0915: Too many statements (60/50) (too-many-statements)
tests/performance_sitespeed_io.py:220:63: W0613: Unused argument 'global_translation' (unused-argument)
tests/performance_sitespeed_io.py:220:83: W0613: Unused argument 'local_translation' (unused-argument)
tests/performance_sitespeed_io.py:305:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/performance_sitespeed_io.py:305:0: R0914: Too many local variables (25/15) (too-many-locals)
tests/performance_sitespeed_io.py:335:12: R1731: Consider using 'biggest = max(biggest, number)' instead of unnecessary if block (consider-using-max-builtin)
tests/performance_sitespeed_io.py:432:19: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/performance_sitespeed_io.py:305:0: R0912: Too many branches (43/12) (too-many-branches)
tests/performance_sitespeed_io.py:305:0: R0915: Too many statements (103/50) (too-many-statements)

**Comment by 7h3Rabbit** [comment]
Solved and closed.
