### ISSUE TITLE
PyLint for Improved Code Quality - tests/software.py

### ISSUE THREAD

**Issue by cockroacher** [Webperf-se/webperf_core#327]
************* Module tests.software
tests/software.py:56:0: C0301: Line too long (108/100) (line-too-long)
tests/software.py:93:0: C0301: Line too long (378/100) (line-too-long)
tests/software.py:97:0: C0301: Line too long (335/100) (line-too-long)
tests/software.py:100:0: C0301: Line too long (213/100) (line-too-long)
tests/software.py:114:0: C0303: Trailing whitespace (trailing-whitespace)
tests/software.py:165:0: C0301: Line too long (122/100) (line-too-long)
tests/software.py:190:0: C0301: Line too long (112/100) (line-too-long)
tests/software.py:208:0: C0303: Trailing whitespace (trailing-whitespace)
tests/software.py:248:0: C0301: Line too long (124/100) (line-too-long)
tests/software.py:287:0: C0301: Line too long (142/100) (line-too-long)
tests/software.py:309:0: C0301: Line too long (142/100) (line-too-long)
tests/software.py:342:0: C0303: Trailing whitespace (trailing-whitespace)
tests/software.py:347:0: C0301: Line too long (142/100) (line-too-long)
tests/software.py:370:0: C0301: Line too long (142/100) (line-too-long)
tests/software.py:413:0: C0301: Line too long (105/100) (line-too-long)
tests/software.py:423:0: C0301: Line too long (104/100) (line-too-long)
tests/software.py:484:0: C0303: Trailing whitespace (trailing-whitespace)
tests/software.py:563:0: C0303: Trailing whitespace (trailing-whitespace)
tests/software.py:620:0: C0301: Line too long (118/100) (line-too-long)
tests/software.py:624:0: C0301: Line too long (104/100) (line-too-long)
tests/software.py:628:0: C0301: Line too long (283/100) (line-too-long)
tests/software.py:634:0: C0301: Line too long (115/100) (line-too-long)
tests/software.py:637:0: C0301: Line too long (165/100) (line-too-long)
tests/software.py:667:0: C0301: Line too long (161/100) (line-too-long)
tests/software.py:696:30: C0303: Trailing whitespace (trailing-whitespace)
tests/software.py:700:0: C0303: Trailing whitespace (trailing-whitespace)
tests/software.py:718:0: C0303: Trailing whitespace (trailing-whitespace)
tests/software.py:723:0: C0301: Line too long (211/100) (line-too-long)
tests/software.py:754:0: C0303: Trailing whitespace (trailing-whitespace)
tests/software.py:814:0: C0301: Line too long (124/100) (line-too-long)
tests/software.py:827:0: C0303: Trailing whitespace (trailing-whitespace)
tests/software.py:832:0: C0301: Line too long (131/100) (line-too-long)
tests/software.py:843:0: C0301: Line too long (106/100) (line-too-long)
tests/software.py:844:0: C0301: Line too long (146/100) (line-too-long)
tests/software.py:845:0: C0301: Line too long (123/100) (line-too-long)
tests/software.py:887:0: C0301: Line too long (127/100) (line-too-long)
tests/software.py:917:0: C0301: Line too long (126/100) (line-too-long)
tests/software.py:920:0: C0301: Line too long (108/100) (line-too-long)
tests/software.py:935:0: C0301: Line too long (130/100) (line-too-long)
tests/software.py:942:0: C0301: Line too long (115/100) (line-too-long)
tests/software.py:950:0: C0301: Line too long (113/100) (line-too-long)
tests/software.py:965:0: C0301: Line too long (103/100) (line-too-long)
tests/software.py:974:0: C0301: Line too long (125/100) (line-too-long)
tests/software.py:999:0: C0301: Line too long (137/100) (line-too-long)
tests/software.py:1011:0: C0301: Line too long (138/100) (line-too-long)
tests/software.py:1427:0: R0915: Too many statements (59/50) (too-many-statements)
tests/software.py:1427:58: W0613: Unused argument 'origin_domain' (unused-argument)
tests/software.py:1459:12: W0612: Unused variable 'matchNum' (unused-variable)
tests/software.py:1509:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/software.py:1517:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/software.py:1517:0: R0914: Too many local variables (22/15) (too-many-locals)
tests/software.py:1543:16: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/software.py:1545:12: C0103: Variable name "matchNum" doesn't conform to snake_case naming style (invalid-name)
tests/software.py:1556:47: C0121: Comparison 'match_name == None' should be 'match_name is None' (singleton-comparison)
tests/software.py:1558:50: C0121: Comparison 'match_version == None' should be 'match_version is None' (singleton-comparison)
tests/software.py:1517:0: R0912: Too many branches (24/12) (too-many-branches)
tests/software.py:1517:0: R0915: Too many statements (56/50) (too-many-statements)
tests/software.py:1517:67: W0613: Unused argument 'origin_domain' (unused-argument)
tests/software.py:1545:12: W0612: Unused variable 'matchNum' (unused-variable)
tests/software.py:1595:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/software.py:1596:4: W0622: Redefining built-in 'dir' (redefined-builtin)
tests/software.py:1599:16: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/software.py:1601:20: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/software.py:1605:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
tests/software.py:1606:16: E1101: Module 'json' has no 'load' member (no-member)
tests/software.py:1609:16: C0103: Argument name "langCode" doesn't conform to snake_case naming style (invalid-name)
tests/software.py:1633:4: C0206: Consider iterating with .items() (consider-using-dict-items)
tests/software.py:1633:15: C0201: Consider iterating the dictionary directly instead of calling .keys() (consider-iterating-dictionary)
tests/software.py:1637:19: E1101: Module 'json' has no 'dumps' member (no-member)
tests/software.py:5:0: C0411: standard import "hashlib" should be placed before third party imports "PIL.ExifTags.TAGS", "PIL.Image" (wrong-import-order)
tests/software.py:6:0: C0411: standard import "pathlib.Path" should be placed before third party imports "PIL.ExifTags.TAGS", "PIL.Image" (wrong-import-order)
tests/software.py:7:0: C0411: standard import "shutil" should be placed before third party imports "PIL.ExifTags.TAGS", "PIL.Image" (wrong-import-order)
tests/software.py:9:0: C0411: standard import "os" should be placed before third party imports "PIL.ExifTags.TAGS", "PIL.Image" and first party import "models.Rating"  (wrong-import-order)
tests/software.py:10:0: C0411: standard import "json" should be placed before third party imports "PIL.ExifTags.TAGS", "PIL.Image" and first party import "models.Rating"  (wrong-import-order)
tests/software.py:11:0: C0411: third party import "config" should be placed before first party import "models.Rating"  (wrong-import-order)
tests/software.py:12:0: C0411: standard import "re" should be placed before third party imports "PIL.ExifTags.TAGS", "PIL.Image", "config" and first party import "models.Rating"  (wrong-import-order)
tests/software.py:14:0: C0411: standard import "urllib.parse.urlparse" should be placed before third party imports "PIL.ExifTags.TAGS", "PIL.Image", "config" and first party import "models.Rating"  (wrong-import-order)
tests/software.py:17:0: C0411: standard import "datetime" should be placed before third party imports "PIL.ExifTags.TAGS", "PIL.Image", "config" and first party imports "models.Rating", "tests.utils.*", "tests.sitespeed_base.get_result"  (wrong-import-order)
tests/software.py:18:0: C0411: third party import "packaging.version" should be placed before first party imports "models.Rating", "tests.utils.*", "tests.sitespeed_base.get_result"  (wrong-import-order)
tests/software.py:19:0: C0411: standard import "gettext" should be placed before third party imports "PIL.ExifTags.TAGS", "PIL.Image", "config", "packaging.version" and first party imports "models.Rating", "tests.utils.*", "tests.sitespeed_base.get_result"  (wrong-import-order)
tests/software.py:3:0: W0611: Unused GPSTAGS imported from PIL.ExifTags (unused-import)
tests/software.py:7:0: W0611: Unused import shutil (unused-import)
tests/software.py:15:0: W0614: Unused import(s) request_timeout, useragent, sys, socket, ssl, time, requests, urllib, uuid, dns, IP2Location, ip2location_db, ex, googlePageSpeedApiKey, gitHubApiKey, dns_server, change_url_to_test_url, get_cache_path, get_cache_file, has_cache_file, clean_cache_files, set_cache_file, get_content_type, get_url_headers, has_redirect, get_guid, convert_to_seconds, is_sitemap, dns_lookup, dns_response_to_list, get_eu_countries, get_exception_countries, is_country_code_in_eu, is_country_code_in_exception_list, is_country_code_in_eu_or_on_exception_list, get_country_code_from_ip2location, get_best_country_code, get_friendly_url_name, BeautifulSoup, ParseResult and urlunparse from wildcard import of tests.utils (unused-wildcard-import)

**Comment by 7h3Rabbit** [comment]
tests/software.py:31:0: C0301: Line too long (108/100) (line-too-long)
tests/software.py:68:0: C0301: Line too long (378/100) (line-too-long)
tests/software.py:72:0: C0301: Line too long (335/100) (line-too-long)
tests/software.py:75:0: C0301: Line too long (213/100) (line-too-long)
tests/software.py:89:0: C0303: Trailing whitespace (trailing-whitespace)
tests/software.py:140:0: C0301: Line too long (122/100) (line-too-long)
tests/software.py:165:0: C0301: Line too long (112/100) (line-too-long)
tests/software.py:183:0: C0303: Trailing whitespace (trailing-whitespace)
tests/software.py:223:0: C0301: Line too long (135/100) (line-too-long)
tests/software.py:262:0: C0301: Line too long (153/100) (line-too-long)
tests/software.py:284:0: C0301: Line too long (153/100) (line-too-long)
tests/software.py:317:0: C0303: Trailing whitespace (trailing-whitespace)
tests/software.py:322:0: C0301: Line too long (153/100) (line-too-long)
tests/software.py:345:0: C0301: Line too long (153/100) (line-too-long)
tests/software.py:368:0: C0301: Line too long (107/100) (line-too-long)
tests/software.py:378:0: C0301: Line too long (110/100) (line-too-long)
tests/software.py:388:0: C0301: Line too long (116/100) (line-too-long)
tests/software.py:398:0: C0301: Line too long (115/100) (line-too-long)
tests/software.py:459:0: C0303: Trailing whitespace (trailing-whitespace)
tests/software.py:538:0: C0303: Trailing whitespace (trailing-whitespace)
tests/software.py:595:0: C0301: Line too long (118/100) (line-too-long)
tests/software.py:599:0: C0301: Line too long (104/100) (line-too-long)
tests/software.py:603:0: C0301: Line too long (283/100) (line-too-long)
tests/software.py:609:0: C0301: Line too long (115/100) (line-too-long)
tests/software.py:612:0: C0301: Line too long (165/100) (line-too-long)
tests/software.py:1065:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/software.py:1065:0: R0914: Too many local variables (20/15) (too-many-locals)
tests/software.py:1072:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
tests/software.py:[1138](https://github.com/Webperf-se/webperf_core/actions/runs/8588845582/job/23534216988#step:6:1139):7: C0121: Comparison 'global_cookies != None' should be 'global_cookies is not None' (singleton-comparison)
tests/software.py:1065:0: R0912: Too many branches (13/12) (too-many-branches)
tests/software.py:1155:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/software.py:1158:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/software.py:1164:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/software.py:1198:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/software.py:1198:0: R0914: Too many local variables (30/15) (too-many-locals)
tests/software.py:1202:7: C0121: Comparison 'response_mimetype == None' should be 'response_mimetype is None' (singleton-comparison)
tests/software.py:1226:16: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/software.py:1228:12: C0103: Variable name "matchNum" doesn't conform to snake_case naming style (invalid-name)
tests/software.py:1239:47: C0121: Comparison 'match_name == None' should be 'match_name is None' (singleton-comparison)
tests/software.py:1243:50: C0121: Comparison 'match_version == None' should be 'match_version is None' (singleton-comparison)
tests/software.py:1247:48: C0121: Comparison 'match_github_owner == None' should be 'match_github_owner is None' (singleton-comparison)
tests/software.py:1259:47: C0121: Comparison 'match_github_repo == None' should be 'match_github_repo is None' (singleton-comparison)
tests/software.py:1267:30: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/software.py:1293:23: C0121: Comparison 'match_github_owner != None' should be 'match_github_owner is not None' (singleton-comparison)
tests/software.py:1295:23: C0121: Comparison 'match_github_repo != None' should be 'match_github_repo is not None' (singleton-comparison)
tests/software.py:1297:23: C0121: Comparison 'license_url != None' should be 'license_url is not None' (singleton-comparison)
tests/software.py:1198:0: R0912: Too many branches (33/12) (too-many-branches)
tests/software.py:1198:0: R0915: Too many statements (83/50) (too-many-statements)
tests/software.py:1228:12: W0612: Unused variable 'matchNum' (unused-variable)
tests/software.py:1308:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/software.py:1308:0: R0913: Too many arguments (7/5) (too-many-arguments)
tests/software.py:1327:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/software.py:1327:0: R0914: Too many local variables (19/15) (too-many-locals)
tests/software.py:1344:16: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/software.py:1346:12: C0103: Variable name "matchNum" doesn't conform to snake_case naming style (invalid-name)
tests/software.py:[1357](https://github.com/Webperf-se/webperf_core/actions/runs/8588845582/job/23534216988#step:6:1358):47: C0121: Comparison 'match_name == None' should be 'match_name is None' (singleton-comparison)
tests/software.py:1359:50: C0121: Comparison 'match_version == None' should be 'match_version is None' (singleton-comparison)
tests/software.py:1327:0: R0912: Too many branches (21/12) (too-many-branches)
tests/software.py:1346:12: W0612: Unused variable 'matchNum' (unused-variable)
tests/software.py:1393:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/software.py:1401:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/software.py:1401:0: R0914: Too many local variables (23/15) (too-many-locals)
tests/software.py:1431:16: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/software.py:1433:12: C0103: Variable name "matchNum" doesn't conform to snake_case naming style (invalid-name)
tests/software.py:1444:47: C0121: Comparison 'match_name == None' should be 'match_name is None' (singleton-comparison)
tests/software.py:1446:50: C0121: Comparison 'match_version == None' should be 'match_version is None' (singleton-comparison)
tests/software.py:1401:0: R0912: Too many branches (25/12) (too-many-branches)
tests/software.py:1401:0: R0915: Too many statements (59/50) (too-many-statements)
tests/software.py:1401:58: W0613: Unused argument 'origin_domain' (unused-argument)
tests/software.py:1433:12: W0612: Unused variable 'matchNum' (unused-variable)
tests/software.py:1483:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/software.py:1491:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/software.py:1491:0: R0914: Too many local variables (22/15) (too-many-locals)
tests/software.py:1517:16: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/software.py:1519:12: C0103: Variable name "matchNum" doesn't conform to snake_case naming style (invalid-name)
tests/software.py:1530:47: C0121: Comparison 'match_name == None' should be 'match_name is None' (singleton-comparison)
tests/software.py:1532:50: C0121: Comparison 'match_version == None' should be 'match_version is None' (singleton-comparison)
tests/software.py:1491:0: R0912: Too many branches (24/12) (too-many-branches)
tests/software.py:1491:0: R0915: Too many statements (56/50) (too-many-statements)
tests/software.py:1491:67: W0613: Unused argument 'origin_domain' (unused-argument)
tests/software.py:1519:12: W0612: Unused variable 'matchNum' (unused-variable)
tests/software.py:1569:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/software.py:1570:4: W0622: Redefining built-in 'dir' (redefined-builtin)
tests/software.py:1573:16: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/software.py:1575:20: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/software.py:1579:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
tests/software.py:1604:4: C0206: Consider iterating with .items() (consider-using-dict-items)
tests/software.py:1604:15: C0201: Consider iterating the dictionary directly instead of calling .keys() (consider-iterating-dictionary)
tests/software.py:16:0: C0412: Imports from package tests are not grouped (ungrouped-imports)

**Comment by 7h3Rabbit** [comment]
> ************* Module tests.software
> tests/software.py:2:0: C0302: Too many lines in module (1612/1000) (too-many-lines)
> tests/software.py:67:0: C0116: Missing function or method docstring (missing-function-docstring)
> tests/software.py:145:0: C0116: Missing function or method docstring (missing-function-docstring)
> tests/software.py:165:0: C0116: Missing function or method docstring (missing-function-docstring)
> tests/software.py:165:0: R0911: Too many return statements (9/6) (too-many-return-statements)
> tests/software.py:188:0: C0116: Missing function or method docstring (missing-function-docstring)
> tests/software.py:188:0: R0914: Too many local variables (17/15) (too-many-locals)
> tests/software.py:188:0: R0912: Too many branches (49/12) (too-many-branches)
> tests/software.py:188:0: R0915: Too many statements (166/50) (too-many-statements)
> tests/software.py:188:81: W0613: Unused argument 'url' (unused-argument)
> tests/software.py:405:0: C0116: Missing function or method docstring (missing-function-docstring)
> tests/software.py:405:49: W0613: Unused argument 'global_translation' (unused-argument)
> tests/software.py:421:0: C0116: Missing function or method docstring (missing-function-docstring)
> tests/software.py:426:4: R1702: Too many nested blocks (6/5) (too-many-nested-blocks)
> tests/software.py:426:4: R1702: Too many nested blocks (6/5) (too-many-nested-blocks)
> tests/software.py:426:4: R1702: Too many nested blocks (6/5) (too-many-nested-blocks)
> tests/software.py:502:23: W0631: Using possibly undefined loop variable 'tech' (undefined-loop-variable)
> tests/software.py:421:0: R0912: Too many branches (34/12) (too-many-branches)
> tests/software.py:421:0: R0915: Too many statements (65/50) (too-many-statements)
> tests/software.py:525:0: C0116: Missing function or method docstring (missing-function-docstring)
> tests/software.py:554:0: C0116: Missing function or method docstring (missing-function-docstring)
> tests/software.py:572:0: C0116: Missing function or method docstring (missing-function-docstring)
> tests/software.py:627:0: C0116: Missing function or method docstring (missing-function-docstring)
> tests/software.py:643:4: W0702: No exception type(s) specified (bare-except)
> tests/software.py:627:46: W0613: Unused argument 'version' (unused-argument)
> tests/software.py:627:55: W0613: Unused argument 'url' (unused-argument)
> tests/software.py:657:0: C0116: Missing function or method docstring (missing-function-docstring)
> tests/software.py:671:4: W0702: No exception type(s) specified (bare-except)
> tests/software.py:679:7: R1714: Consider merging these comparisons with 'in' by using 'version in (None, '')'. Use a set instead if elements are hashable. (consider-using-in)
> tests/software.py:679:7: C0121: Comparison 'version == None' should be 'version is None' (singleton-comparison)
> tests/software.py:693:0: C0116: Missing function or method docstring (missing-function-docstring)
> tests/software.py:693:0: R0914: Too many local variables (21/15) (too-many-locals)
> tests/software.py:701:11: R0916: Too many boolean expressions in if statement (6/5) (too-many-boolean-expressions)
> tests/software.py:700:4: R1702: Too many nested blocks (6/5) (too-many-nested-blocks)
> tests/software.py:753:47: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
> tests/software.py:759:11: C0121: Comparison 'match['version'] == None' should be 'match['version'] is None' (singleton-comparison)
> tests/software.py:771:8: W0702: No exception type(s) specified (bare-except)
> tests/software.py:785:12: W0702: No exception type(s) specified (bare-except)
> tests/software.py:788:12: R1723: Unnecessary "elif" after "break", remove the leading "el" from "elif" (no-else-break)
> tests/software.py:693:0: R0912: Too many branches (41/12) (too-many-branches)
> tests/software.py:693:0: R0915: Too many statements (91/50) (too-many-statements)
> tests/software.py:822:0: C0116: Missing function or method docstring (missing-function-docstring)
> tests/software.py:822:32: W0613: Unused argument 'tmp_list' (unused-argument)
> tests/software.py:836:0: C0116: Missing function or method docstring (missing-function-docstring)
> tests/software.py:836:28: W0613: Unused argument 'tmp_list' (unused-argument)
> tests/software.py:836:44: W0613: Unused argument 'result_folder_name' (unused-argument)
> tests/software.py:836:64: W0613: Unused argument 'nof_tries' (unused-argument)
> tests/software.py:846:0: C0116: Missing function or method docstring (missing-function-docstring)
> tests/software.py:846:31: W0613: Unused argument 'tmp_list' (unused-argument)
> tests/software.py:846:41: W0613: Unused argument 'item' (unused-argument)
> tests/software.py:846:47: W0613: Unused argument 'result_folder_name' (unused-argument)
> tests/software.py:846:67: W0613: Unused argument 'nof_tries' (unused-argument)
> tests/software.py:850:0: C0116: Missing function or method docstring (missing-function-docstring)
> tests/software.py:850:0: R0914: Too many local variables (26/15) (too-many-locals)
> tests/software.py:869:16: C0103: Variable name "matchNum" doesn't conform to snake_case naming style (invalid-name)
> tests/software.py:882:24: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
> tests/software.py:893:24: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
> tests/software.py:895:24: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
> tests/software.py:911:12: W0702: No exception type(s) specified (bare-except)
> tests/software.py:925:19: C0121: Comparison 'tag == None' should be 'tag is None' (singleton-comparison)
> tests/software.py:926:26: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
> tests/software.py:934:16: W0702: No exception type(s) specified (bare-except)
> tests/software.py:943:24: C0103: Variable name "matchNum" doesn't conform to snake_case naming style (invalid-name)
> tests/software.py:947:27: C0121: Comparison 'tech_name != None' should be 'tech_name is not None' (singleton-comparison)
> tests/software.py:947:49: C0121: Comparison 'tech_version == None' should be 'tech_version is None' (singleton-comparison)
> tests/software.py:956:32: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
> tests/software.py:958:27: C0121: Comparison 'tech_version != None' should be 'tech_version is not None' (singleton-comparison)
> tests/software.py:972:32: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
> tests/software.py:983:32: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
> tests/software.py:853:4: R1702: Too many nested blocks (6/5) (too-many-nested-blocks)
> tests/software.py:984:21: R1714: Consider merging these comparisons with 'in' by using 'tag_name in ('artist', 'xpauthor')'. Use a set instead if elements are hashable. (consider-using-in)
> tests/software.py:990:24: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
> tests/software.py:1002:24: C0103: Variable name "matchNum" doesn't conform to snake_case naming style (invalid-name)
> tests/software.py:1006:27: C0121: Comparison 'tech_name != None' should be 'tech_name is not None' (singleton-comparison)
> tests/software.py:1006:49: C0121: Comparison 'tech_version == None' should be 'tech_version is None' (singleton-comparison)
> tests/software.py:1014:32: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
> tests/software.py:1016:27: C0121: Comparison 'tech_version != None' should be 'tech_version is not None' (singleton-comparison)
> tests/software.py:1024:32: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
> tests/software.py:1026:27: C0121: Comparison 'os_name != None' should be 'os_name is not None' (singleton-comparison)
> tests/software.py:1035:32: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
> tests/software.py:853:4: R1702: Too many nested blocks (6/5) (too-many-nested-blocks)
> tests/software.py:1042:24: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
> tests/software.py:1050:24: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
> tests/software.py:1061:24: W0631: Using possibly undefined loop variable 'match' (undefined-loop-variable)
> tests/software.py:1063:24: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
> tests/software.py:1063:52: W0631: Using possibly undefined loop variable 'match' (undefined-loop-variable)
> tests/software.py:1076:24: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
> tests/software.py:1076:52: W0631: Using possibly undefined loop variable 'match' (undefined-loop-variable)
> tests/software.py:850:0: R0912: Too many branches (35/12) (too-many-branches)
> tests/software.py:850:0: R0915: Too many statements (105/50) (too-many-statements)
> tests/software.py:850:64: W0613: Unused argument 'nof_tries' (unused-argument)
> tests/software.py:869:16: W0612: Unused variable 'matchNum' (unused-variable)
> tests/software.py:935:20: W0612: Unused variable 'a' (unused-variable)
> tests/software.py:1079:0: C0116: Missing function or method docstring (missing-function-docstring)
> tests/software.py:1079:0: R0914: Too many local variables (20/15) (too-many-locals)
> tests/software.py:1079:0: R0912: Too many branches (14/12) (too-many-branches)
> tests/software.py:1153:0: C0116: Missing function or method docstring (missing-function-docstring)
> tests/software.py:1156:0: C0116: Missing function or method docstring (missing-function-docstring)
> tests/software.py:1162:0: C0116: Missing function or method docstring (missing-function-docstring)
> tests/software.py:1199:0: C0116: Missing function or method docstring (missing-function-docstring)
> tests/software.py:1199:0: R0914: Too many local variables (30/15) (too-many-locals)
> tests/software.py:1227:16: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
> tests/software.py:1229:12: C0103: Variable name "matchNum" doesn't conform to snake_case naming style (invalid-name)
> tests/software.py:1199:0: R0912: Too many branches (33/12) (too-many-branches)
> tests/software.py:1199:0: R0915: Too many statements (83/50) (too-many-statements)
> tests/software.py:1229:12: W0612: Unused variable 'matchNum' (unused-variable)
> tests/software.py:1305:0: C0116: Missing function or method docstring (missing-function-docstring)
> tests/software.py:1305:0: R0913: Too many arguments (7/5) (too-many-arguments)
> tests/software.py:1324:0: C0116: Missing function or method docstring (missing-function-docstring)
> tests/software.py:1324:0: R0914: Too many local variables (19/15) (too-many-locals)
> tests/software.py:1341:16: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
> tests/software.py:1343:12: C0103: Variable name "matchNum" doesn't conform to snake_case naming style (invalid-name)
> tests/software.py:1324:0: R0912: Too many branches (21/12) (too-many-branches)
> tests/software.py:1343:12: W0612: Unused variable 'matchNum' (unused-variable)
> tests/software.py:1390:0: C0116: Missing function or method docstring (missing-function-docstring)
> tests/software.py:1398:0: C0116: Missing function or method docstring (missing-function-docstring)
> tests/software.py:1398:0: R0914: Too many local variables (23/15) (too-many-locals)
> tests/software.py:1428:16: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
> tests/software.py:1430:12: C0103: Variable name "matchNum" doesn't conform to snake_case naming style (invalid-name)
> tests/software.py:1398:0: R0912: Too many branches (25/12) (too-many-branches)
> tests/software.py:1398:0: R0915: Too many statements (59/50) (too-many-statements)
> tests/software.py:1398:58: W0613: Unused argument 'origin_domain' (unused-argument)
> tests/software.py:1430:12: W0612: Unused variable 'matchNum' (unused-variable)
> tests/software.py:1480:0: C0116: Missing function or method docstring (missing-function-docstring)
> tests/software.py:1488:0: C0116: Missing function or method docstring (missing-function-docstring)
> tests/software.py:1488:0: R0914: Too many local variables (22/15) (too-many-locals)
> tests/software.py:1514:16: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
> tests/software.py:1516:12: C0103: Variable name "matchNum" doesn't conform to snake_case naming style (invalid-name)
> tests/software.py:1488:0: R0912: Too many branches (24/12) (too-many-branches)
> tests/software.py:1488:0: R0915: Too many statements (56/50) (too-many-statements)
> tests/software.py:1488:67: W0613: Unused argument 'origin_domain' (unused-argument)
> tests/software.py:1516:12: W0612: Unused variable 'matchNum' (unused-variable)
> tests/software.py:1566:0: C0116: Missing function or method docstring (missing-function-docstring)
> tests/software.py:1601:4: C0206: Consider iterating with .items() (consider-using-dict-items)
> tests/software.py:1601:15: C0201: Consider iterating the dictionary directly instead of calling .keys() (consider-iterating-dictionary)

**Comment by cockroacher** [comment]
After discussions it has been concluded that the long term goal is to convert this (or most parts of it) to sitespeed plugin.
Because of this, it has been deemed a waste of time to continue this conversion. Time is better spent to improve our regression tests.
