### ISSUE TITLE
PyLint for Improved Code Quality - tests/standard_files.py

### ISSUE THREAD

**Issue by cockroacher** [Webperf-se/webperf_core#328]
************* Module tests.standard_files
tests/standard_files.py:77:0: C0301: Line too long (204/100) (line-too-long)
tests/standard_files.py:209:0: C0301: Line too long (108/100) (line-too-long)
tests/standard_files.py:243:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
tests/standard_files.py:269:0: C0325: Unnecessary parens after 'not' keyword (superfluous-parens)
tests/standard_files.py:278:0: C0325: Unnecessary parens after 'not' keyword (superfluous-parens)
tests/standard_files.py:156:5: W0511: TODO: validate first feed (fixme)
tests/standard_files.py:1:0: C0114: Missing module docstring (missing-module-docstring)
tests/standard_files.py:4:0: E0401: Unable to import 'requests' (import-error)
tests/standard_files.py:6:0: E0401: Unable to import 'bs4' (import-error)
tests/standard_files.py:7:0: E0401: Unable to import 'config' (import-error)
tests/standard_files.py:8:0: W0401: Wildcard import tests.utils (wildcard-import)
tests/standard_files.py:18:16: C0103: Argument name "langCode" doesn't conform to snake_case naming style (invalid-name)
tests/standard_files.py:37:17: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/standard_files.py:40:18: R1735: Consider using '{}' instead of a call to 'dict'. (use-dict-literal)
tests/standard_files.py:71:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/standard_files.py:72:18: R1735: Consider using '{}' instead of a call to 'dict'. (use-dict-literal)
tests/standard_files.py:77:7: C0121: Comparison 'robots_content == None' should be 'robots_content is None' (singleton-comparison)
tests/standard_files.py:91:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/standard_files.py:93:18: R1735: Consider using '{}' instead of a call to 'dict'. (use-dict-literal)
tests/standard_files.py:96:7: C0121: Comparison 'robots_content == None' should be 'robots_content is None' (singleton-comparison)
tests/standard_files.py:123:47: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/standard_files.py:130:47: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
tests/standard_files.py:139:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/standard_files.py:155:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/standard_files.py:158:18: R1735: Consider using '{}' instead of a call to 'dict'. (use-dict-literal)
tests/standard_files.py:159:11: R1734: Consider using [] instead of list() (use-list-literal)
tests/standard_files.py:168:4: W0702: No exception type(s) specified (bare-except)
tests/standard_files.py:191:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/standard_files.py:202:4: W0702: No exception type(s) specified (bare-except)
tests/standard_files.py:214:4: W0702: No exception type(s) specified (bare-except)
tests/standard_files.py:222:4: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
tests/standard_files.py:229:22: R1735: Consider using '{}' instead of a call to 'dict'. (use-dict-literal)
tests/standard_files.py:244:12: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
tests/standard_files.py:252:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/standard_files.py:254:18: R1735: Consider using '{}' instead of a call to 'dict'. (use-dict-literal)
tests/standard_files.py:255:7: C0121: Comparison 'content == None' should be 'content is None' (singleton-comparison)
tests/standard_files.py:3:0: C0411: standard import "datetime" should be placed before first party import "models.Rating"  (wrong-import-order)
tests/standard_files.py:4:0: C0411: third party import "requests" should be placed before first party import "models.Rating"  (wrong-import-order)
tests/standard_files.py:5:0: C0411: standard import "urllib" should be placed before third party import "requests" and first party import "models.Rating"  (wrong-import-order)
tests/standard_files.py:6:0: C0411: third party import "bs4.BeautifulSoup" should be placed before first party import "models.Rating"  (wrong-import-order)
tests/standard_files.py:7:0: C0411: third party import "config" should be placed before first party import "models.Rating"  (wrong-import-order)
tests/standard_files.py:9:0: C0411: standard import "gettext" should be placed before third party imports "requests", "bs4.BeautifulSoup", "config" and first party imports "models.Rating", "tests.utils.*"  (wrong-import-order)
tests/standard_files.py:8:0: W0614: Unused import(s) hashlib, shutil, sys, socket, ssl, json, time, uuid, re, dns, IP2Location, os, ip2location_db, ex, googlePageSpeedApiKey, gitHubApiKey, use_cache, cache_time_delta, dns_server, change_url_to_test_url, is_file_older_than, get_cache_path, get_cache_file, has_cache_file, clean_cache_files, set_cache_file, get_content_type, get_url_headers, has_redirect, get_guid, convert_to_seconds, dns_lookup, dns_response_to_list, get_eu_countries, get_exception_countries, is_country_code_in_eu, is_country_code_in_exception_list, is_country_code_in_eu_or_on_exception_list, get_country_code_from_ip2location, get_best_country_code, get_friendly_url_name, timedelta, Path, ParseResult, urlparse and urlunparse from wildcard import of tests.utils (unused-wildcard-import)

**Comment by 7h3Rabbit** [comment]
a bit smaller list after #243 
************* Module tests.standard_files
tests/standard_files.py:205:17: W0511: TODO: ensure known file extention (fixme)
tests/standard_files.py:214:5: W0511: TODO: validate url encoding (fixme)
tests/standard_files.py:17:0: C0103: Constant name "request_timeout" doesn't conform to UPPER_CASE naming style (invalid-name)
tests/standard_files.py:18:0: C0103: Constant name "useragent" doesn't conform to UPPER_CASE naming style (invalid-name)
tests/standard_files.py:19:0: C0103: Constant name "review_show_improvements_only" doesn't conform to UPPER_CASE naming style (invalid-name)
tests/standard_files.py:22:4: C0103: Constant name "use_detailed_report" doesn't conform to UPPER_CASE naming style (invalid-name)
tests/standard_files.py:25:4: C0103: Constant name "use_detailed_report" doesn't conform to UPPER_CASE naming style (invalid-name)
tests/standard_files.py:87:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/standard_files.py:88:18: R1735: Consider using '{}' instead of a call to 'dict'. (use-dict-literal)
tests/standard_files.py:110:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/standard_files.py:112:18: R1735: Consider using '{}' instead of a call to 'dict'. (use-dict-literal)
tests/standard_files.py:125:12: C0103: Variable name "matchNum" doesn't conform to snake_case naming style (invalid-name)
tests/standard_files.py:110:0: R0912: Too many branches (14/12) (too-many-branches)
tests/standard_files.py:125:12: W0612: Unused variable 'matchNum' (unused-variable)
tests/standard_files.py:176:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/standard_files.py:176:0: R0914: Too many local variables (26/15) (too-many-locals)
tests/standard_files.py:203:11: R1716: Simplify chained comparison between the operands (chained-comparison)
tests/standard_files.py:176:0: R0912: Too many branches (23/12) (too-many-branches)
tests/standard_files.py:176:0: R0915: Too many statements (104/50) (too-many-statements)
tests/standard_files.py:347:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/standard_files.py:363:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/standard_files.py:374:4: W0702: No exception type(s) specified (bare-except)
tests/standard_files.py:397:0: C0116: Missing function or method docstring (missing-function-docstring)
tests/standard_files.py:408:4: W0702: No exception type(s) specified (bare-except)
tests/standard_files.py:421:4: W0702: No exception type(s) specified (bare-except)
tests/standard_files.py:429:4: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
tests/standard_files.py:436:22: R1735: Consider using '{}' instead of a call to 'dict'. (use-dict-literal)
tests/standard_files.py:453:8: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
tests/standard_files.py:459:0: C0116: Missing function or method docstring (missing-function-docstring)

**Comment by 7h3Rabbit** [comment]
Solved and closed
