### ISSUE TITLE
UTF-8 Byte Order Mark Breaks Test

### ISSUE THREAD

**Issue by rabbtekejos** [Webperf-se/webperf_core#443]
I have been investigating why our site got a low score in the standard files sub-category and found that webperf can't handle the presence of a UTF-8 BOM (Byte Order Mark)

If the robots.txt file begins with a BOM and the first row has the sitemap: <url> instruction then webperf will not fetch and process the sitemap.

If the sitemap.xml file begins with a BOM then get_root_element fails to find the root element.

This likely affects other areas of this and other tests as well.

**Comment by 7h3Rabbit** [comment]
@rabbtekejos Please provide one (preferably 5-10 different) url(s) we can reproduce this bug against.

**Comment by 7h3Rabbit** [comment]
Notes for when we have test urls:
It could be because of missing/malformed encoding info in response headers resulting in wrong encoding used when reading file.
We use [get_http_content](https://github.com/Webperf-se/webperf_core/blob/e421184d1493a94693ad9cb65e1a85dd5504fdb5/tests/utils.py#L452)): to get sitemap(s) used [response.text](https://requests.readthedocs.io/en/latest/api/#requests.Response.text) for xml sitemaps.
According to documentation it uses unicode IF encoding can't be determined by response headers.

**Comment by 7h3Rabbit** [comment]
@rabbtekejos I would have preferred url **BUT** I think I see the problem/missing part in your code example.

You are not specifying encoding/charset on this line:
`Response.Headers.ContentType = "text/xml";`
resulting in receiving party MUST use default charset (read: `us-ascii`).

As you are encoding your XML with `utf-8` you need to specify that the xml is using  `utf-8` charset/encoding in the contenttype.
If you change that line to the following it should work:

`Response.Headers.ContentType = "text/xml; charset=utf-8";`

Let me know if that solves your problem :)

**Comment by 7h3Rabbit** [comment]
@rabbtekejos As long as it is not protected behind login it should be possible to access the local website

**Comment by 7h3Rabbit** [comment]
closed as there was no new info in issue for a week.
