### ISSUE TITLE
Sv: Sitemap – kunna packa upp dem - används av Sitevision primärt

### ISSUE THREAD

**Issue by marcusosterberg** [Webperf-se/webperf_core#9]
Tror det är därför det smäller vid .lower() i koden.

Exempelvis på https://www.minmyndighetspost.se/sitemapindex.xml

**Comment by flowertwig-org** [comment]
Can't find a sitemap test in webperf-core, where to find it?

**Comment by marcusosterberg** [comment]
It's still in my local repo. Should we have a feature branch where I can put such code?

**Comment by flowertwig-org** [comment]
If you do, I can look at it and add it to the webperf_core project :)

**Comment by flowertwig-org** [comment]
The error ".lower()" has been fixed in "features" branch.
But this site have 2 other issues:
1. it is pointing to sitemap on http:// and not https:// (AND not responding on http://)
2. It requires redirect as it also points to website without "www."

For now I would vote to mark this as fixed and if there is any other websites (or current one fixes their problems) having this issue we can look at it again.

@marcusosterberg  what do you want to do with this?

**Comment by marcusosterberg** [comment]
See #40 for further problems.
